ARG BASE_IMAGE=ghcr.io/commaai/openpilot-base:latest
FROM ${BASE_IMAGE}

RUN apt update && apt install rsync -y

RUN rm -rf /output/*
RUN mkdir -p /output
RUN touch /output/prebuilt
RUN chmod u+x /output

CMD rm -rf /output/* ; rsync -a --exclude-from=/excluded_file_extensions.txt . /output && \
find /output -type d -exec chmod 755 {} \; && find /output -type f -exec chmod 644 {} \; && \
chmod u+x /output
