name: Build and Publish

on:
  workflow_dispatch:  #  This enables manual triggering
  push:
    branches:
      - master # replace with your branch, if needed

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Set env
        run: |
          echo "Setting up REPO_URL environment variable..."
          REPO="github.com/${{ github.repository }}"
          echo "REPO_URL=https://x-access-token:${GITHUB_TOKEN}@${REPO}.git" >> $GITHUB_ENV
          echo "REPO_URL has been set to: https://x-access-token:${GITHUB_TOKEN}@${REPO}.git"
          echo "VERSION=$(date '+%Y.%m.%d')" >> $GITHUB_ENV
          export SOURCE_DIR=$(git rev-parse --show-toplevel)
          export OUTPUT_DIR=${SOURCE_DIR}/output
          export CI_DIR="${SOURCE_DIR}/release/ci"
          echo "SOURCE_DIR=${SOURCE_DIR}" >> $GITHUB_ENV
          echo "OUTPUT_DIR=${OUTPUT_DIR}" >> $GITHUB_ENV
          echo "CI_DIR=${CI_DIR}" >> $GITHUB_ENV
          echo "DONE"

      - name: Building sunnypilot
        run: |
          echo $VERSION
          echo $SOURCE_DIR
          echo $OUTPUT_DIR
          echo $CI_DIR

          mkdir -p ${OUTPUT_DIR}
          chmod -R u+x ${OUTPUT_DIR}

          echo "Calling to build [${DIR}/build.sh ${SOURCE_DIR} ${OUTPUT_DIR} ${VERSION}]"
          $CI_DIR/build.sh "${SOURCE_DIR}" "${OUTPUT_DIR}" "${VERSION}"
        shell: bash

      - name: Ensuring proper permissions to built files
        run: |
          echo $OUTPUT_DIR

          sudo chmod -R u+x $OUTPUT_DIR

          ls -la $OUTPUT_DIR
          sudo chmod -R a+rwx $OUTPUT_DIR
          ls -la $OUTPUT_DIR

        shell: bash

      - name: Publishing sunnypilot
        run: |
          if [ -z "$DEV_BRANCH" ]; then
            DEV_BRANCH="dev-c3-test"
          fi

          echo ${VERSION}
          echo ${SOURCE_DIR}
          echo ${OUTPUT_DIR}
          echo ${DEV_BRANCH}
          echo ${REPO_URL}
          echo $CI_DIR

          echo "Calling to publish [${DIR}/publish.sh ${SOURCE_DIR} ${OUTPUT_DIR} ${DEV_BRANCH} ${VERSION} ${REPO_URL}]"
          $CI_DIR/publish.sh "${SOURCE_DIR}" "${OUTPUT_DIR}" "${DEV_BRANCH}" "${VERSION}" "${REPO_URL}"
        shell: bash


