name: Build and Publish

on:
  workflow_dispatch:  #  This enables manual triggering
  push:
    branches:
      - master # replace with your branch, if needed

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Set env
        run: |
          echo "Setting up REPO_URL environment variable..."
          echo "REPO_URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "REPO_URL has been set to: ${{ github.server_url }}/${{ github.repository }}.git"
          echo "VERSION=$(date '+%Y.%m.%d')" >> $GITHUB_ENV
          export SOURCE_DIR=$(git rev-parse --show-toplevel)
          export OUTPUT_DIR=${SOURCE_DIR}/output
          echo "SOURCE_DIR=${SOURCE_DIR}" >> $GITHUB_ENV
          echo "OUTPUT_DIR=${OUTPUT_DIR}" >> $GITHUB_ENV
          echo "DONE"

      - name: Building sunnypilot
        run: |
          echo $VERSION
          echo $SOURCE_DIR
          echo $OUTPUT_DIR

          pwd
          mkdir -p $$OUTPUT_DIR
          ls -la $SOURCE_DIR

          ls -la $OUTPUT_DIR

          chmod -R u+x $OUTPUT_DIR

          echo "Calling to build [${DIR}/build.sh ${SOURCE_DIR} ${OUTPUT_DIR} ${VERSION}]"
          $DIR/build.sh "${SOURCE_DIR}" "${OUTPUT_DIR}" "${VERSION}"
        shell: bash

      - name: Ensuring proper permissions to built files
        run: |
          echo $OUTPUT_DIR

          sudo chmod -R u+x $OUTPUT_DIR
        shell: bash

      - name: Publishing sunnypilot
        run: |
          if [ -z "$DEV_BRANCH" ]; then
            DEV_BRANCH="dev-c3-test"
          fi

          if [ -z "$GIT_ORIGIN" ]; then
            GIT_ORIGIN="git@github.com:devtekve/openpilot-og.git" #This is a default that should be changed
            echo "No GIT_ORIGIN provided, we will use the default [${GIT_ORIGIN}]"
          fi

          echo ${VERSION}
          echo ${SOURCE_DIR}
          echo ${OUTPUT_DIR}
          echo ${DEV_BRANCH}
          echo ${REPO_URL}

          echo "Calling to publish [${DIR}/publish.sh ${SOURCE_DIR} ${OUTPUT_DIR} ${DEV_BRANCH} ${VERSION} ${GIT_ORIGIN}]"
          $DIR/publish.sh "${SOURCE_DIR}" "${OUTPUT_DIR}" "${DEV_BRANCH}" "${VERSION}" "${GIT_ORIGIN}"
        shell: bash


