name: Build and Publish

on:
  workflow_dispatch:  #  This enables manual triggering
  push:
    branches:
      - master # replace with your branch, if needed

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute Scripts
        run: |
          sudo chmod +x ./release/ci/build_and_publish.sh
          sudo ./release/ci/build_and_publish.sh "dev-c3-test"
