name: Build and Publish

on:
  workflow_dispatch:  #  This enables manual triggering
  push:
    branches:
      - master # replace with your branch, if needed

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Set env
        run: |
          echo "Setting up REPO_URL environment variable..."
          echo "REPO_URL=${{ github.server_url }}/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "REPO_URL has been set to: ${{ github.server_url }}/${{ github.repository }}.git"

      - name: Execute Scripts
        run: |
          chmod +x ./release/ci/build_and_publish.sh
          ./release/ci/build_and_publish.sh "dev-c3-test" "${REPO_URL}"
        shell: bash
